### ISSUE TITLE
Missing option to specify main xsd file

### ISSUE THREAD

**Issue by polentino** [alisiikh/gradle-scalaxb-plugin#7]
It would be nice to have an extra option, i.e. `mainSchema`, to specifcy from which `xsd` file start the parsing operation.

The reason is that I have a complex xsd structure, divided into 16 different xsd files. When I try to execute the plugin, I get lots of errors like

> Error: Referenced type {http://www.w3.org/2000/09/xmldsig#} <type> was not found.

However, if open a terminal, and execute(1) `scalaxb main.xsd`, I will see a lot of warning about missing types but then, after all the `xsd`s are parsed, the corresponding scala classes are all generated.

(1) I installed the command line utility as explained here http://scalaxb.org/setup

**Comment by olisikh** [comment]
There's a problem in the gradle plugin atm, it spawns scalaxb java process per each xsd file, but it should just take all of them available and do the processing in one go.

I believe there's no need to change the order of the files passed to scalaxb as it should figure out the order as it builds AST out of the xsd and produces the output as the last step (AFAIK).

Thanks for reporting it.

**Comment by olisikh** [comment]
Could you please try it with the version 0.1.0 https://plugins.gradle.org/plugin/com.github.alisiikh.scalaxb?

It should pick up all of your xsd files in the folder and respect the imports.

@polentino

**Comment by polentino** [comment]
Thank you for the prompt reply @alisiikh ; I've tried with the new version of the plugin, and indeed it works!
Have a nice day :)
